"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { useForm, useWatch } from "react-hook-form";
import { z } from "zod";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { Employee, Team } from "@/lib/types";

const employeeSchema = z.object({ employee_id: z.string().min(1, "Employee ID is required"), name: z.string().min(1, "Name is required"), email: z.string().email("Enter a valid email"), role: z.string().min(1, "Role is required"), department: z.string().min(1, "Department is required"), manager_id: z.string(), employment_status: z.enum(["ACTIVE", "INACTIVE", "ON_LEAVE"]) });
const projectSchema = z.object({ project_id: z.string().min(1, "Project ID is required"), name: z.string().min(1, "Name is required"), description: z.string(), owner_employee_id: z.string(), department: z.string(), status: z.enum(["PLANNED", "ACTIVE", "IN_PROGRESS", "ON_HOLD", "COMPLETED", "ARCHIVED"]), github_organization: z.string(), github_repository: z.string(), github_repository_id: z.string(), github_default_branch: z.string(), github_installation_id: z.string(), jira_cloud_id: z.string(), jira_project_key: z.string() });
const teamSchema = z.object({ team_id: z.string().min(1, "Team ID is required"), name: z.string().min(1, "Name is required"), description: z.string(), team_lead_id: z.string(), status: z.enum(["ACTIVE", "INACTIVE"]) });
const membershipSchema = z.object({ employee_id: z.string().min(1, "Employee is required"), role: z.string().min(1, "Role is required"), allocation_percentage: z.coerce.number().min(0).max(100), team_id: z.string(), status: z.enum(["ACTIVE", "INACTIVE"]) });
const taskSchema = z.object({ task_id: z.string().min(1, "Task ID is required"), title: z.string().min(1, "Title is required"), description: z.string(), jira_issue_key: z.string(), assignee_id: z.string(), team_id: z.string(), priority: z.enum(["LOW", "MEDIUM", "HIGH", "CRITICAL"]), estimated_hours: z.coerce.number().min(0).nullable(), actual_hours: z.coerce.number().min(0), acceptance_criteria: z.string() });

type FormProps<T> = { defaultValues?: Partial<T>; onSubmit: (value: T) => void | Promise<void>; submitting?: boolean; submitLabel?: string };
function FieldError({ message }: { message?: string }) { return message ? <small className="field-error">{message}</small> : null; }
function FormActions({ submitting, submitLabel }: { submitting?: boolean; submitLabel: string }) { return <button className="button primary" type="submit" disabled={submitting}>{submitting ? "Saving..." : submitLabel}</button>; }

export function EmployeeForm({ defaultValues, onSubmit, submitting, submitLabel = "Save employee" }: FormProps<z.infer<typeof employeeSchema>>) {
  const { register, handleSubmit, formState: { errors } } = useForm<z.input<typeof employeeSchema>, unknown, z.output<typeof employeeSchema>>({ resolver: zodResolver(employeeSchema), defaultValues: { employee_id: "", manager_id: "", employment_status: "ACTIVE", ...defaultValues } });
  return <form className="form-panel" onSubmit={handleSubmit(onSubmit)}><label>Employee ID<input {...register("employee_id")} readOnly={Boolean(defaultValues?.employee_id)} /> <FieldError message={errors.employee_id?.message} /></label><label>Name<input {...register("name")} /> <FieldError message={errors.name?.message} /></label><label>Email<input type="email" {...register("email")} /> <FieldError message={errors.email?.message} /></label><label>Role<input {...register("role")} /> <FieldError message={errors.role?.message} /></label><label>Department<input {...register("department")} /> <FieldError message={errors.department?.message} /></label><label>Manager ID<input {...register("manager_id")} /></label><label>Employment status<select {...register("employment_status")}><option>ACTIVE</option><option>INACTIVE</option><option>ON_LEAVE</option></select></label><FormActions submitting={submitting} submitLabel={submitLabel} /></form>;
}

export function ProjectForm({ defaultValues, onSubmit, submitting, submitLabel = "Save project" }: FormProps<z.infer<typeof projectSchema>>) {
  const { register, handleSubmit, formState: { errors } } = useForm<z.input<typeof projectSchema>, unknown, z.output<typeof projectSchema>>({ resolver: zodResolver(projectSchema), defaultValues: { project_id: "", description: "", owner_employee_id: "", department: "", status: "PLANNED", github_organization: "", github_repository: "", github_repository_id: "", github_default_branch: "main", github_installation_id: "", jira_cloud_id: "", jira_project_key: "", ...defaultValues } });
  return <form className="form-panel" onSubmit={handleSubmit(onSubmit)}><label>Project ID<input {...register("project_id")} readOnly={Boolean(defaultValues?.project_id)} /> <FieldError message={errors.project_id?.message} /></label><label>Name<input {...register("name")} /> <FieldError message={errors.name?.message} /></label><label>Description<textarea {...register("description")} /></label><label>Owner employee ID<input {...register("owner_employee_id")} /></label><label>Department<input {...register("department")} /></label><label>Status<select {...register("status")}><option>PLANNED</option><option>ACTIVE</option><option>IN_PROGRESS</option><option>ON_HOLD</option><option>COMPLETED</option><option>ARCHIVED</option></select></label><p className="form-context">GitHub metadata (no secrets)</p><label>Organization<input {...register("github_organization")} /></label><label>Repository<input {...register("github_repository")} /></label><label>Repository ID<input {...register("github_repository_id")} /></label><label>Default branch<input {...register("github_default_branch")} /></label><label>Installation ID<input {...register("github_installation_id")} /></label><p className="form-context">Jira metadata (no secrets)</p><label>Cloud ID<input {...register("jira_cloud_id")} /></label><label>Project key<input {...register("jira_project_key")} /></label><FormActions submitting={submitting} submitLabel={submitLabel} /></form>;
}

export function TeamForm({ defaultValues, onSubmit, submitting, submitLabel = "Save team" }: FormProps<z.infer<typeof teamSchema>>) {
  const { register, handleSubmit, formState: { errors } } = useForm<z.infer<typeof teamSchema>>({ resolver: zodResolver(teamSchema), defaultValues: { team_id: "", description: "", team_lead_id: "", status: "ACTIVE", ...defaultValues } });
  return <form className="form-panel" onSubmit={handleSubmit(onSubmit)}><label>Team ID<input {...register("team_id")} readOnly={Boolean(defaultValues?.team_id)} /> <FieldError message={errors.team_id?.message} /></label><label>Name<input {...register("name")} /> <FieldError message={errors.name?.message} /></label><label>Description<textarea {...register("description")} /></label><label>Team lead ID<input {...register("team_lead_id")} /></label><label>Status<select {...register("status")}><option>ACTIVE</option><option>INACTIVE</option></select></label><FormActions submitting={submitting} submitLabel={submitLabel} /></form>;
}

export function ProjectMembershipForm({ employees, teams, defaultValues, onSubmit, submitting }: FormProps<z.infer<typeof membershipSchema>> & { employees: Employee[]; teams: Team[] }) {
  const { register, handleSubmit, formState: { errors } } = useForm<z.input<typeof membershipSchema>, unknown, z.output<typeof membershipSchema>>({ resolver: zodResolver(membershipSchema), defaultValues: { employee_id: "", role: "Member", allocation_percentage: 100, team_id: "", status: "ACTIVE", ...defaultValues } });
  const selectedEmployee = employees.find((employee) => employee.employee_id === defaultValues?.employee_id);
  return <form className="form-panel" onSubmit={handleSubmit(onSubmit)}><label>Employee{defaultValues?.employee_id ? <><input value={selectedEmployee?.name ?? defaultValues.employee_id} readOnly /><input type="hidden" {...register("employee_id")} /></> : <select {...register("employee_id")}><option value="">Select employee</option>{employees.map((employee) => <option key={employee.employee_id} value={employee.employee_id}>{employee.name}</option>)}</select>}<FieldError message={errors.employee_id?.message} /></label><label>Role<input {...register("role")} /></label><label>Allocation percentage<input type="number" min="0" max="100" {...register("allocation_percentage")} /><FieldError message={errors.allocation_percentage?.message} /></label><label>Team<select {...register("team_id")}><option value="">No team</option>{teams.map((team) => <option key={team.team_id} value={team.team_id}>{team.name}</option>)}</select></label><label>Status<select {...register("status")}><option>ACTIVE</option><option>INACTIVE</option></select></label><FormActions submitting={submitting} submitLabel="Save membership" /></form>;
}

export function TaskForm({ projectId, employees, teams, defaultValues, onSubmit, submitting, submitLabel = "Save task" }: FormProps<z.infer<typeof taskSchema>> & { projectId: string; employees: Employee[]; teams: Team[] }) {
  const { control, register, handleSubmit, setValue, formState: { errors } } = useForm<z.input<typeof taskSchema>, unknown, z.output<typeof taskSchema>>({ resolver: zodResolver(taskSchema), defaultValues: { task_id: "", title: "", description: "", jira_issue_key: "", assignee_id: "", team_id: "", priority: "MEDIUM", estimated_hours: null, actual_hours: 0, acceptance_criteria: "", ...defaultValues } });
  const selectedTeam = useWatch({ control, name: "team_id" }); const [teamMemberships, setTeamMemberships] = useState<{ teamId: string; employeeIds: string[] } | null>(null); const teamMemberIds = teamMemberships?.teamId === selectedTeam ? teamMemberships.employeeIds : null; const teamMembers = selectedTeam && teamMemberIds ? employees.filter((employee) => teamMemberIds.includes(employee.employee_id)) : selectedTeam ? [] : employees;
  useEffect(() => { if (!selectedTeam) return; let active = true; void api.teamEmployees(projectId, selectedTeam).then((members) => { if (active) setTeamMemberships({ teamId: selectedTeam, employeeIds: members.map((member) => member.employee_id) }); }).catch(() => { if (active) setTeamMemberships({ teamId: selectedTeam, employeeIds: [] }); }); return () => { active = false; }; }, [projectId, selectedTeam]);
  return <form className="form-panel" onSubmit={handleSubmit(onSubmit)}><p className="form-context">Project: {projectId}</p><label>Task ID<input {...register("task_id")} readOnly={Boolean(defaultValues?.task_id)} /> <FieldError message={errors.task_id?.message} /></label><label>Title<input {...register("title")} /> <FieldError message={errors.title?.message} /></label><label>Description<textarea {...register("description")} /></label><label>Jira issue key<input {...register("jira_issue_key")} /></label><label>Team<select {...register("team_id", { onChange: () => setValue("assignee_id", "") })}><option value="">No team</option>{teams.map((team) => <option key={team.team_id} value={team.team_id}>{team.name}</option>)}</select></label>{selectedTeam && <small className="form-hint">Only members of the selected project team can be assigned.</small>}<label>Assignee<select {...register("assignee_id")}><option value="">Unassigned</option>{teamMembers.map((employee) => <option key={employee.employee_id} value={employee.employee_id}>{employee.name}</option>)}</select></label><label>Priority<select {...register("priority")}><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select><FieldError message={errors.priority?.message} /></label><label>Estimated hours<input type="number" min="0" step="0.5" {...register("estimated_hours")} /></label><label>Actual hours<input type="number" min="0" step="0.5" {...register("actual_hours")} /></label><label>Acceptance criteria<textarea placeholder="One criterion per line" {...register("acceptance_criteria")} /></label><FormActions submitting={submitting} submitLabel={submitLabel} /></form>;
}