"use client";

import Link from "next/link";
import { useState } from "react";
import { useAddEmployeeToProject, useAddEmployeeToTeam, useCreateTeam, useProjectEmployees, useProjectTeams, useRemoveEmployeeFromProject, useRemoveEmployeeFromTeam, useTeam, useTeamEmployees, useUpdateProjectMembership, useUpdateTeam } from "@/lib/hooks";
import { useEmployees } from "@/lib/hooks";
import type { Membership } from "@/lib/types";
import { ProjectMembershipForm, TeamForm } from "./forms";
import { EmptyState, ErrorState, StatusBadge } from "./ui";
import { useToast } from "./toast";

export function ProjectPeople({ projectId }: { projectId: string }) {
  const memberships = useProjectEmployees(projectId); const employees = useEmployees(); const teams = useProjectTeams(projectId); const add = useAddEmployeeToProject(); const update = useUpdateProjectMembership(); const remove = useRemoveEmployeeFromProject(); const toast = useToast(); const [editing, setEditing] = useState<Membership | null>(null); const [showAdd, setShowAdd] = useState(false);
  const knownEmployees = employees.data?.items ?? []; const knownTeams = teams.data ?? [];
  async function save(value: { employee_id: string; role: string; allocation_percentage: number; team_id: string; status: "ACTIVE" | "INACTIVE" }) { try { if (editing) { await update.mutateAsync({ projectId, employeeId: editing.employee_id, body: { team_id: value.team_id || null, role: value.role, allocation_percentage: value.allocation_percentage, status: value.status } }); toast.success("Project membership updated."); setEditing(null); } else { await add.mutateAsync({ projectId, body: { employee_id: value.employee_id, team_id: value.team_id || null, role: value.role, allocation_percentage: value.allocation_percentage } }); toast.success("Employee added to project."); setShowAdd(false); } } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Membership could not be saved."); } }
  async function removeMember(employeeId: string, name: string) { if (!window.confirm(`Remove ${name} from this project?`)) return; try { await remove.mutateAsync({ projectId, employeeId }); toast.success("Employee removed from project."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Membership could not be removed."); } }
  if (memberships.isError || employees.isError || teams.isError) return <ErrorState message="Project people could not be loaded." />;
  return <div className="panel relationship-panel"><div className="panel-title">People <button className="button secondary compact" onClick={() => setShowAdd((current) => !current)}>+ Add employee</button></div>{showAdd && <ProjectMembershipForm employees={knownEmployees.filter((employee) => !(memberships.data ?? []).some((member) => member.employee_id === employee.employee_id))} teams={knownTeams} onSubmit={save} submitting={add.isPending} />}{editing && <ProjectMembershipForm employees={knownEmployees} teams={knownTeams} defaultValues={{ employee_id: editing.employee_id, role: editing.role, allocation_percentage: editing.allocation_percentage, team_id: editing.team_id ?? "", status: editing.status }} onSubmit={save} submitting={update.isPending} />}{memberships.data?.length ? memberships.data.map((member) => { const employee = knownEmployees.find((item) => item.employee_id === member.employee_id); return <div className="relationship-row" key={member.employee_id}><div><strong>{employee?.name ?? member.employee_id}</strong><small>{member.role} · {member.allocation_percentage}% allocation</small></div><StatusBadge value={member.status} /><button className="button secondary compact" onClick={() => setEditing(member)}>Edit</button><button className="button danger compact" onClick={() => void removeMember(member.employee_id, employee?.name ?? member.employee_id)}>Remove</button></div>; }) : <EmptyState title="No employees assigned to this project">Add an employee to start building project context.</EmptyState>}</div>;
}

export function TeamsPage({ projectId }: { projectId: string }) {
  const teams = useProjectTeams(projectId); const create = useCreateTeam(); const update = useUpdateTeam(); const toast = useToast(); const [showCreate, setShowCreate] = useState(false); const [editing, setEditing] = useState<string | null>(null);
  async function save(value: { team_id: string; name: string; description: string; team_lead_id: string; status: "ACTIVE" | "INACTIVE" }) { try { if (editing) { await update.mutateAsync({ projectId, teamId: editing, body: value }); toast.success("Team updated successfully."); setEditing(null); } else { await create.mutateAsync({ projectId, body: value }); toast.success("Team created successfully."); setShowCreate(false); } } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Team could not be saved."); } }
  return <div className="page"><Link className="back-link" href={`/dashboard/projects/${projectId}`}>← Project overview</Link><div className="page-heading"><div><p className="eyebrow">Project / {projectId}</p><h1>Teams</h1><p>Teams are scoped to this project and cannot be moved between projects.</p></div><button className="button primary" onClick={() => setShowCreate((current) => !current)}>+ Create team</button></div>{showCreate && <TeamForm onSubmit={save} submitting={create.isPending} submitLabel="Create team" />}{teams.isError ? <ErrorState message="Teams could not be loaded." /> : <div className="panel">{teams.data?.length ? teams.data.map((team) => <div className="relationship-row" key={team.team_id}><div><Link href={`/dashboard/projects/${projectId}/teams/${team.team_id}`}><strong>{team.name}</strong></Link><small>{team.team_id} · {team.team_lead_id ?? "No lead"}</small></div><StatusBadge value={team.status} /><button className="button secondary compact" onClick={() => setEditing(team.team_id)}>Edit</button>{editing === team.team_id && <TeamForm defaultValues={{ team_id: team.team_id, name: team.name, description: team.description ?? "", team_lead_id: team.team_lead_id ?? "", status: team.status }} onSubmit={save} submitting={update.isPending} />}</div>) : <EmptyState title="No teams yet">Create a team for this project.</EmptyState>}</div>}</div>;
}

export function TeamDetail({ projectId, teamId }: { projectId: string; teamId: string }) {
  const team = useTeam(projectId, teamId); const members = useTeamEmployees(projectId, teamId); const employees = useEmployees(); const add = useAddEmployeeToTeam(); const remove = useRemoveEmployeeFromTeam(); const toast = useToast(); const [showAdd, setShowAdd] = useState(false);
  async function addMember(employeeId: string) { try { await add.mutateAsync({ projectId, teamId, employeeId }); toast.success("Employee added to team."); setShowAdd(false); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Employee could not be added to team."); } }
  async function removeMember(employeeId: string, name: string) { if (!window.confirm(`Remove ${name} from this team?`)) return; try { await remove.mutateAsync({ projectId, teamId, employeeId }); toast.success("Employee removed from team."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Employee could not be removed from team."); } }
  if (team.isError || members.isError) return <div className="page"><ErrorState message="Team could not be loaded." /></div>;
  const projectEmployees = employees.data?.items ?? []; const memberIds = new Set((members.data ?? []).map((member) => member.employee_id));
  return <div className="page"><Link className="back-link" href={`/dashboard/projects/${projectId}/teams`}>← Project teams</Link><div className="page-heading"><div><p className="eyebrow">Team / {teamId}</p><h1>{team.data?.name ?? teamId}</h1><p>{team.data?.description ?? "No team description has been added."}</p></div><button className="button primary" onClick={() => setShowAdd((current) => !current)}>+ Add employee</button></div>{showAdd && <div className="form-panel"><p className="form-context">Only employees already belonging to this project can be added.</p>{projectEmployees.filter((employee) => !memberIds.has(employee.employee_id)).map((employee) => <button className="button secondary" key={employee.employee_id} onClick={() => void addMember(employee.employee_id)}>{employee.name}</button>)}{projectEmployees.every((employee) => memberIds.has(employee.employee_id)) && <small>No eligible project employees available.</small>}</div>}<div className="panel">{members.data?.length ? members.data.map((member) => { const employee = projectEmployees.find((item) => item.employee_id === member.employee_id); return <div className="relationship-row" key={member.employee_id}><div><strong>{employee?.name ?? member.employee_id}</strong><small>{member.role} · {member.allocation_percentage}% allocation</small></div><button className="button danger compact" onClick={() => void removeMember(member.employee_id, employee?.name ?? member.employee_id)}>Remove</button></div>; }) : <EmptyState title="No employees assigned to this team">Add a project employee to this team.</EmptyState>}</div></div>;
}