"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { Task } from "@/lib/types";
import { EmptyState, ErrorState, ProgressBar, StatusBadge } from "./ui";
import { useEmployees, useProjectEmployees, useProjectTeams, useUpdateTask } from "@/lib/hooks";
import { TaskForm } from "./forms";
import { useToast } from "./toast";

export function TaskDetail({ projectId, taskId }: { projectId: string; taskId: string }) {
  const [task, setTask] = useState<Task | null>(null); const [error, setError] = useState<string | null>(null); const [showEdit, setShowEdit] = useState(false); const update = useUpdateTask(); const employees = useProjectEmployees(projectId); const allEmployees = useEmployees(); const teams = useProjectTeams(projectId); const toast = useToast();
  useEffect(() => { void api.task(projectId, taskId).then(setTask).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : "The API is unavailable.")); }, [projectId, taskId]);
  if (error) return <div className="page"><ErrorState message={error} /></div>; if (!task) return <div className="page"><div className="hero-skeleton" /></div>;
  async function save(value: { task_id: string; title: string; description: string; jira_issue_key: string; assignee_id: string; team_id: string; priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; estimated_hours: number | null; actual_hours: number; acceptance_criteria: string }) { try { const updated = await update.mutateAsync({ projectId, taskId, body: { title: value.title, description: value.description || null, jira_issue_key: value.jira_issue_key || null, assignee_id: value.assignee_id || null, team_id: value.team_id || null, priority: value.priority, estimated_hours: value.estimated_hours, actual_hours: value.actual_hours, acceptance_criteria: value.acceptance_criteria.split("\n").map((item) => item.trim()).filter(Boolean) } }); setTask(updated); setShowEdit(false); toast.success("Task updated successfully."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Task could not be updated."); } }
  const projectEmployeeIds = new Set((employees.data ?? []).map((membership) => membership.employee_id)); const employeeRows = (allEmployees.data?.items ?? []).filter((employee) => projectEmployeeIds.has(employee.employee_id));
  return <div className="page"><Link className="back-link" href={`/dashboard/projects/${projectId}`}>← {projectId}</Link><div className="page-heading detail-heading"><div><p className="eyebrow">Task detail · {task.task_id}</p><h1>{task.title}</h1><p>{task.description ?? "No description has been added."}</p></div><div><StatusBadge value={task.status} /><button className="button secondary" onClick={() => setShowEdit((current) => !current)}>Edit task</button></div></div>{showEdit && <TaskForm projectId={projectId} employees={employeeRows} teams={teams.data ?? []} defaultValues={{ task_id: task.task_id, title: task.title, description: task.description ?? "", jira_issue_key: task.jira_issue_key ?? "", assignee_id: task.assignee_id ?? "", team_id: task.team_id ?? "", priority: task.priority, estimated_hours: task.estimated_hours, actual_hours: task.actual_hours, acceptance_criteria: task.acceptance_criteria.join("\n") }} onSubmit={save} submitting={update.isPending} submitLabel="Save task" />}<div className="detail-metrics"><div><span>Progress</span><strong>{task.progress}%</strong><ProgressBar value={task.progress} /></div><div><span>Priority</span><strong>{task.priority}</strong><small>{task.jira_issue_key ?? "No Jira issue"}</small></div><div><span>Assignee</span><strong>{task.assignee_id ?? "Unassigned"}</strong><small>{task.team_id ? `Team ${task.team_id}` : "No team"}</small></div></div><div className="section-heading"><h2>Why Astra thinks this is the current state</h2></div><div className="panel"><EmptyState title="No evidence has been collected yet">Evidence APIs are not exposed by the current backend. This panel is reserved for GitHub, Jira, agent, and meeting evidence.</EmptyState></div><div className="section-heading"><h2>Task history</h2></div><div className="panel history"><div><span className="history-dot" /><strong>{task.status.replaceAll("_", " ")}</strong><small>Current state · updated {new Date(task.updated_at).toLocaleDateString()}</small></div></div></div>;
}