"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { useCreateTask, useEmployees, useProjectEmployees, useProjectTeams } from "@/lib/hooks";
import { useToast } from "./toast";
import { TaskForm } from "./forms";
import type { Employee, Project, Task } from "@/lib/types";
import { EmptyState, ErrorState, Skeleton, StatusBadge } from "./ui";

type TaskWithProject = { task: Task; project: Project };

export function TasksOverview() {
  const [items, setItems] = useState<TaskWithProject[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [showCreate, setShowCreate] = useState(false); const [selectedProjectId, setSelectedProjectId] = useState("");
  const createTask = useCreateTask(); const projectMemberships = useProjectEmployees(selectedProjectId); const projectTeams = useProjectTeams(selectedProjectId); const allEmployees = useEmployees(); const toast = useToast();
  useEffect(() => { let active = true; void (async () => { try { const projectPage = await api.projects(); const pages = await Promise.all(projectPage.items.map(async (project) => ({ project, tasks: (await api.projectTasks(project.project_id)).items }))); if (active) { setProjects(projectPage.items); setItems(pages.flatMap(({ project, tasks }) => tasks.map((task) => ({ project, task })))); } } catch (caught) { if (active) setError(caught instanceof Error ? caught.message : "Tasks could not be loaded."); } finally { if (active) setLoading(false); } })(); return () => { active = false; }; }, []);
  const filtered = useMemo(() => items.filter(({ task, project }) => (status === "ALL" || task.status === status) && `${task.title} ${task.task_id} ${project.name}`.toLowerCase().includes(query.toLowerCase())), [items, query, status]);
  const selectedProject = projects.find((project) => project.project_id === selectedProjectId);
  const memberIds = new Set((projectMemberships.data ?? []).filter((membership) => membership.status === "ACTIVE").map((membership) => membership.employee_id));
  const eligibleEmployees: Employee[] = (allEmployees.data?.items ?? []).filter((employee) => memberIds.has(employee.employee_id) && employee.employment_status === "ACTIVE");
  async function saveTask(value: { task_id: string; title: string; description: string; jira_issue_key: string; assignee_id: string; team_id: string; priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; estimated_hours: number | null; actual_hours: number; acceptance_criteria: string }) {
    if (!selectedProject) return;
    try {
      const task = await createTask.mutateAsync({ projectId: selectedProject.project_id, body: { ...value, description: value.description || null, jira_issue_key: value.jira_issue_key || null, assignee_id: value.assignee_id || null, team_id: value.team_id || null, status: "NOT_STARTED", progress: 0, acceptance_criteria: value.acceptance_criteria.split("\n").map((item) => item.trim()).filter(Boolean) } });
      setItems((current) => [...current, { task, project: selectedProject }]); setShowCreate(false); toast.success("Task created successfully.");
    } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Task could not be created."); }
  }
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">Astra intelligence</p><h1>Tasks</h1><p>Every task across the workspace, with project context preserved.</p></div><div><span className="task-count">{items.length} tasks</span><button className="button primary" onClick={() => setShowCreate((current) => !current)}>{showCreate ? "Cancel" : "+ Create task"}</button></div></div>{showCreate && <><label className="project-select">Project<select aria-label="Select project" value={selectedProjectId} onChange={(event) => setSelectedProjectId(event.target.value)}><option value="">Select a project</option>{projects.map((project) => <option key={project.project_id} value={project.project_id}>{project.name}</option>)}</select></label>{selectedProjectId && (projectMemberships.isLoading || projectTeams.isLoading || allEmployees.isLoading) ? <div className="workload"><Skeleton /><Skeleton /></div> : selectedProject && (projectMemberships.isError || projectTeams.isError || allEmployees.isError) ? <ErrorState message="Project assignment options could not be loaded." /> : selectedProject && <TaskForm projectId={selectedProjectId} employees={eligibleEmployees} teams={(projectTeams.data ?? []).filter((team) => team.status === "ACTIVE")} onSubmit={saveTask} submitting={createTask.isPending} submitLabel="Create task" />}</>}{error ? <ErrorState message={error} /> : <div className="toolbar task-toolbar"><input aria-label="Search tasks" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tasks..." /><select aria-label="Filter task status" value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">All statuses</option><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="BLOCKED">Blocked</option><option value="LIKELY_COMPLETE">Likely complete</option><option value="VERIFIED_COMPLETE">Verified complete</option></select></div>}{error ? null : <div className="panel">{loading ? <div className="workload"><Skeleton /><Skeleton /><Skeleton /><Skeleton /></div> : filtered.length === 0 ? <EmptyState title={items.length ? "No matching tasks" : "No tasks yet"}>{items.length ? "Try a different search or status." : "Create a task from a project to start tracking work."}</EmptyState> : filtered.map(({ task, project }) => <div className="task-row global-task-row" key={`${project.project_id}:${task.task_id}`}><Link href={`/dashboard/tasks/${project.project_id}/${task.task_id}`}>{task.title}<small>{task.task_id} · {project.name}</small></Link><StatusBadge value={task.status} /><span>{task.progress}%</span><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span></div>)}</div>}</div>;
}