"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { api } from "@/lib/api";
import { useCreateEmployee, useCreateTask, useEmployees, useProjectEmployees, useProjectTeams, useUpdateEmployee } from "@/lib/hooks";
import { useToast } from "./toast";
import { EmployeeForm, TaskForm } from "./forms";
import type { Employee, Task } from "@/lib/types";
import { EmptyState, ErrorState, Skeleton, StatCard, StatusBadge } from "./ui";

export function WorkforcePage() {
  const [employees, setEmployees] = useState<Employee[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [showCreate, setShowCreate] = useState(false); const createEmployee = useCreateEmployee(); const toast = useToast(); const router = useRouter();
  useEffect(() => { void api.employees().then((result) => setEmployees(result.items)).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : "The API is unavailable.")).finally(() => setLoading(false)); }, []);
  const active = employees.filter((employee) => employee.employment_status === "ACTIVE");
  async function submitEmployee(value: Parameters<typeof api.createEmployee>[0] & { employment_status?: string }) { try { const created = await createEmployee.mutateAsync(value); toast.success("Employee created successfully."); setEmployees((current) => [...current, created]); setShowCreate(false); router.push(`/dashboard/workforce/employees/${created.employee_id}`); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Employee could not be created."); } }
  return <div className="page"><div className="page-heading"><div><p className="eyebrow">Workspace / Workforce</p><h1>Workforce intelligence</h1><p>Understand allocation, task progress, and observable activity without reducing people to a score.</p></div><button className="button primary" onClick={() => setShowCreate((current) => !current)}>+ Add employee</button></div>{showCreate && <EmployeeForm onSubmit={submitEmployee} submitting={createEmployee.isPending} submitLabel="Create employee" />}{error ? <ErrorState message={error} /> : <><div className="stats-grid stats-four">{loading ? [1, 2, 3, 4].map((item) => <div className="stat-card" key={item}><Skeleton /></div>) : <><StatCard label="Total employees" value={employees.length} detail="in directory" /><StatCard label="Active employees" value={active.length} detail="employment status" accent="green" /><StatCard label="Agent online" value={active.filter((employee) => employee.agent.status === "ONLINE").length} detail="observable connection" accent="blue" /><StatCard label="Activity" value="—" detail="agent API not connected" accent="yellow" /></>}</div><div className="section-heading"><h2>Employee allocation</h2><span className="eyebrow">Workload · activity · contribution</span></div><div className="panel">{loading ? <div className="workload"><Skeleton /><Skeleton /><Skeleton /></div> : employees.length === 0 ? <EmptyState title="No employees yet">Add employees through the management API to see allocation here.</EmptyState> : employees.map((employee) => <div className="employee-row" key={employee.employee_id}><div className="person"><div className="avatar">{employee.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div><div><Link href={`/dashboard/workforce/employees/${employee.employee_id}`}>{employee.name}</Link><small>{employee.role} · {employee.department}</small></div></div><span>{employee.employment_status}</span><StatusBadge value={employee.agent.status} /><span className="muted-text">Tasks available on employee view</span></div>)}</div></>}</div>;
}

export function EmployeeDetail({ employeeId }: { employeeId: string }) {
  const [employee, setEmployee] = useState<Employee | null>(null); const [tasks, setTasks] = useState<Task[]>([]); const [error, setError] = useState<string | null>(null); const [showEdit, setShowEdit] = useState(false); const updateEmployee = useUpdateEmployee(); const toast = useToast();
  useEffect(() => { void Promise.all([api.employee(employeeId), api.employeeTasks(employeeId)]).then(([employeeResult, taskResult]) => { setEmployee(employeeResult); setTasks(taskResult.items); }).catch((caught: unknown) => setError(caught instanceof Error ? caught.message : "The API is unavailable.")); }, [employeeId]);
  if (error) return <div className="page"><ErrorState message={error} /></div>; if (!employee) return <div className="page"><Skeleton className="hero-skeleton" /></div>;
  async function saveEmployee(value: Parameters<typeof api.updateEmployee>[1]) { try { const updated = await updateEmployee.mutateAsync({ id: employeeId, body: value }); setEmployee(updated); setShowEdit(false); toast.success("Employee updated successfully."); } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Employee could not be updated."); } }
  return <div className="page"><Link className="back-link" href="/dashboard/workforce">← Workforce</Link><div className="page-heading detail-heading"><div className="person hero-person"><div className="avatar large">{employee.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div><div><p className="eyebrow">Employee workspace</p><h1>{employee.name}</h1><p>{employee.role} · {employee.department}</p></div></div><div><StatusBadge value={employee.agent.status} /><button className="button secondary" onClick={() => setShowEdit((current) => !current)}>Edit employee</button></div></div>{showEdit && <EmployeeForm defaultValues={{ employee_id: employee.employee_id, name: employee.name, email: employee.email, role: employee.role, department: employee.department, manager_id: employee.manager_id ?? "", employment_status: employee.employment_status }} onSubmit={saveEmployee} submitting={updateEmployee.isPending} /> }<div className="detail-metrics"><div><span>Assigned tasks</span><strong>{tasks.length}</strong><small>from task state</small></div><div><span>In progress</span><strong>{tasks.filter((task) => task.status === "IN_PROGRESS").length}</strong><small>currently moving</small></div><div><span>Completed</span><strong>{tasks.filter((task) => task.status.includes("COMPLETE")).length}</strong><small>verified progress</small></div></div><div className="section-heading"><h2>Current work</h2></div><div className="panel">{tasks.length ? tasks.map((task) => <div className="task-row" key={task.task_id}><span>{task.title}<small>{task.project_id} · {task.task_id}</small></span><StatusBadge value={task.status} /><span>{task.progress}%</span></div>) : <EmptyState title="No assigned tasks">This employee has no tasks in the current backend view.</EmptyState>}</div><div className="section-heading"><h2>Activity and contributions</h2></div><div className="panel"><EmptyState title="No activity data available yet">Connect the Astra desktop agent to start collecting work activity. GitHub, Jira, and meeting contributions will appear here when those integrations expose data.</EmptyState></div></div>;
}

export function ProjectTasks({ projectId }: { projectId: string }) {
  const [tasks, setTasks] = useState<Task[]>([]); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [showCreate, setShowCreate] = useState(false); const create = useCreateTask(); const employees = useProjectEmployees(projectId); const allEmployees = useEmployees(); const teams = useProjectTeams(projectId); const toast = useToast();
  useEffect(() => { let active = true; void api.projectTasks(projectId).then((result) => { if (active) setTasks(result.items); }).catch((caught: unknown) => { if (active) setError(caught instanceof Error ? caught.message : "The API is unavailable."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [projectId]);
  async function save(value: { task_id: string; title: string; description: string; jira_issue_key: string; assignee_id: string; team_id: string; priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"; estimated_hours: number | null; actual_hours: number; acceptance_criteria: string }) {
    try {
      const created = await create.mutateAsync({ projectId, body: { ...value, description: value.description || null, jira_issue_key: value.jira_issue_key || null, assignee_id: value.assignee_id || null, team_id: value.team_id || null, status: "NOT_STARTED", progress: 0, acceptance_criteria: value.acceptance_criteria.split("\n").map((item) => item.trim()).filter(Boolean) } });
      setTasks((current) => [...current.filter((task) => task.task_id !== created.task_id), created]); setShowCreate(false); toast.success("Task created successfully.");
      try { const refreshed = await api.projectTasks(projectId); setTasks(refreshed.items); } catch { toast.error("Task was created, but the project task list could not be refreshed."); }
    } catch (caught) { toast.error(caught instanceof Error ? caught.message : "Task could not be created."); }
  }
  const activeMemberships = (employees.data ?? []).filter((membership) => membership.status === "ACTIVE"); const projectEmployeeIds = new Set(activeMemberships.map((membership) => membership.employee_id)); const projectEmployees = (allEmployees.data?.items ?? []).filter((employee) => projectEmployeeIds.has(employee.employee_id) && employee.employment_status === "ACTIVE"); const projectTeams = (teams.data ?? []).filter((team) => team.status === "ACTIVE"); const assignmentLoading = employees.isLoading || allEmployees.isLoading || teams.isLoading; const assignmentError = employees.isError || allEmployees.isError || teams.isError;
  return <div className="page"><Link className="back-link" href={`/dashboard/projects/${projectId}`}>← Project overview</Link><div className="page-heading"><div><p className="eyebrow">Project / {projectId}</p><h1>Tasks</h1><p>Tasks for this project, with team and employee assignments.</p></div><button className="button primary" type="button" onClick={() => setShowCreate((current) => !current)}>{showCreate ? "Cancel" : "+ Create task"}</button></div>{showCreate && (assignmentLoading ? <div className="workload"><Skeleton /><Skeleton /></div> : <>{assignmentError && <p className="form-hint">Assignment options could not be loaded. You can still create an unassigned task; reload this page to retry.</p>}<TaskForm projectId={projectId} employees={projectEmployees} teams={projectTeams} onSubmit={save} submitting={create.isPending} submitLabel="Create task" /></>)}{error ? <ErrorState message={error} /> : <div className="panel">{loading ? <div className="workload"><Skeleton /><Skeleton /><Skeleton /></div> : tasks.length ? tasks.map((task) => <div className="task-row" key={task.task_id}><Link href={`/dashboard/tasks/${projectId}/${task.task_id}`}>{task.title}<small>{task.task_id}</small></Link><StatusBadge value={task.status} /><span>{task.progress}%</span><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span></div>) : <EmptyState title="No tasks yet">Create the first task for this project.</EmptyState>}</div>}</div>;
}

export function ComingSoon({ title, detail }: { title: string; detail: string }) { return <div className="page"><div className="page-heading"><div><p className="eyebrow">Astra intelligence</p><h1>{title}</h1><p>{detail}</p></div></div><div className="panel"><EmptyState title="Coming soon">This surface is ready for the backend contract when the corresponding API is available.</EmptyState></div></div>; }