"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "./api";

export const queryKeys = { employees: ["employees"] as const, employee: (id: string) => ["employees", id] as const, employeeProjects: (id: string) => ["employees", id, "projects"] as const, employeeTasks: (id: string) => ["employees", id, "tasks"] as const, projects: ["projects"], project: (id: string) => ["projects", id] as const, projectEmployees: (id: string) => ["projects", id, "employees"] as const, projectTeams: (id: string) => ["projects", id, "teams"] as const, projectTasks: (id: string) => ["projects", id, "tasks"] as const, task: (projectId: string, taskId: string) => ["projects", projectId, "tasks", taskId] as const, team: (projectId: string, teamId: string) => ["projects", projectId, "teams", teamId] as const, teamEmployees: (projectId: string, teamId: string) => ["projects", projectId, "teams", teamId, "employees"] as const };

export function useEmployees() { return useQuery({ queryKey: queryKeys.employees, queryFn: () => api.employees() }); }
export function useEmployee(id: string) { return useQuery({ queryKey: queryKeys.employee(id), queryFn: () => api.employee(id), enabled: Boolean(id) }); }
export function useProjects() { return useQuery({ queryKey: queryKeys.projects, queryFn: () => api.projects() }); }
export function useProject(id: string) { return useQuery({ queryKey: queryKeys.project(id), queryFn: () => api.project(id), enabled: Boolean(id) }); }
export function useProjectEmployees(id: string) { return useQuery({ queryKey: queryKeys.projectEmployees(id), queryFn: () => api.projectEmployees(id), enabled: Boolean(id) }); }
export function useProjectTeams(id: string) { return useQuery({ queryKey: queryKeys.projectTeams(id), queryFn: () => api.projectTeams(id), enabled: Boolean(id) }); }
export function useProjectTasks(id: string) { return useQuery({ queryKey: queryKeys.projectTasks(id), queryFn: () => api.projectTasks(id), enabled: Boolean(id) }); }
export function useEmployeeProjects(id: string) { return useQuery({ queryKey: queryKeys.employeeProjects(id), queryFn: () => api.employeeProjects(id), enabled: Boolean(id) }); }
export function useEmployeeTasks(id: string) { return useQuery({ queryKey: queryKeys.employeeTasks(id), queryFn: () => api.employeeTasks(id), enabled: Boolean(id) }); }
export function useTeam(projectId: string, teamId: string) { return useQuery({ queryKey: queryKeys.team(projectId, teamId), queryFn: () => api.team(projectId, teamId), enabled: Boolean(projectId && teamId) }); }
export function useTeamEmployees(projectId: string, teamId: string) { return useQuery({ queryKey: queryKeys.teamEmployees(projectId, teamId), queryFn: () => api.teamEmployees(projectId, teamId), enabled: Boolean(projectId && teamId) }); }
export function useTask(projectId: string, taskId: string) { return useQuery({ queryKey: queryKeys.task(projectId, taskId), queryFn: () => api.task(projectId, taskId), enabled: Boolean(projectId && taskId) }); }

function invalidateProject(client: ReturnType<typeof useQueryClient>, projectId: string) { void client.invalidateQueries({ queryKey: queryKeys.project(projectId) }); void client.invalidateQueries({ queryKey: queryKeys.projects }); }
function invalidateMembership(client: ReturnType<typeof useQueryClient>, projectId: string, employeeId: string) { void client.invalidateQueries({ queryKey: queryKeys.projectEmployees(projectId) }); void client.invalidateQueries({ queryKey: queryKeys.employeeProjects(employeeId) }); invalidateProject(client, projectId); }

export function useCreateEmployee() { const client = useQueryClient(); return useMutation({ mutationFn: api.createEmployee, onSuccess: () => void client.invalidateQueries({ queryKey: queryKeys.employees }) }); }
export function useUpdateEmployee() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, body }: Parameters<typeof api.updateEmployee>[0] extends string ? { id: string; body: Parameters<typeof api.updateEmployee>[1] } : never) => api.updateEmployee(id, body), onSuccess: (_, variables) => { void client.invalidateQueries({ queryKey: queryKeys.employees }); void client.invalidateQueries({ queryKey: queryKeys.employee(variables.id) }); } }); }
export function useCreateProject() { const client = useQueryClient(); return useMutation({ mutationFn: api.createProject, onSuccess: () => void client.invalidateQueries({ queryKey: queryKeys.projects }) }); }
export function useUpdateProject() { const client = useQueryClient(); return useMutation({ mutationFn: ({ id, body }: { id: string; body: Parameters<typeof api.updateProject>[1] }) => api.updateProject(id, body), onSuccess: (_, variables) => { invalidateProject(client, variables.id); } }); }
export function useCreateTeam() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, body }: { projectId: string; body: Parameters<typeof api.createTeam>[1] }) => api.createTeam(projectId, body), onSuccess: (_, variables) => { void client.invalidateQueries({ queryKey: queryKeys.projectTeams(variables.projectId) }); invalidateProject(client, variables.projectId); } }); }
export function useUpdateTeam() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, teamId, body }: { projectId: string; teamId: string; body: Parameters<typeof api.updateTeam>[2] }) => api.updateTeam(projectId, teamId, body), onSuccess: (_, variables) => { void client.invalidateQueries({ queryKey: queryKeys.projectTeams(variables.projectId) }); void client.invalidateQueries({ queryKey: queryKeys.team(variables.projectId, variables.teamId) }); } }); }
export function useAddEmployeeToProject() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, body }: { projectId: string; body: Parameters<typeof api.addProjectEmployee>[1] }) => api.addProjectEmployee(projectId, body), onSuccess: (_, variables) => invalidateMembership(client, variables.projectId, variables.body.employee_id) }); }
export function useUpdateProjectMembership() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, employeeId, body }: { projectId: string; employeeId: string; body: Parameters<typeof api.updateMembership>[2] }) => api.updateMembership(projectId, employeeId, body), onSuccess: (_, variables) => invalidateMembership(client, variables.projectId, variables.employeeId) }); }
export function useRemoveEmployeeFromProject() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, employeeId }: { projectId: string; employeeId: string }) => api.removeProjectEmployee(projectId, employeeId), onSuccess: (_, variables) => invalidateMembership(client, variables.projectId, variables.employeeId) }); }
export function useAddEmployeeToTeam() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, teamId, employeeId }: { projectId: string; teamId: string; employeeId: string }) => api.addTeamEmployee(projectId, teamId, { employee_id: employeeId }), onSuccess: (_, variables) => { void client.invalidateQueries({ queryKey: queryKeys.teamEmployees(variables.projectId, variables.teamId) }); invalidateMembership(client, variables.projectId, variables.employeeId); } }); }
export function useRemoveEmployeeFromTeam() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, teamId, employeeId }: { projectId: string; teamId: string; employeeId: string }) => api.removeTeamEmployee(projectId, teamId, employeeId), onSuccess: (_, variables) => { void client.invalidateQueries({ queryKey: queryKeys.teamEmployees(variables.projectId, variables.teamId) }); invalidateMembership(client, variables.projectId, variables.employeeId); } }); }
export function useCreateTask() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, body }: { projectId: string; body: Parameters<typeof api.createTask>[1] }) => api.createTask(projectId, body), onSuccess: (task, variables) => { void client.invalidateQueries({ queryKey: queryKeys.projectTasks(variables.projectId) }); invalidateProject(client, variables.projectId); if (task.assignee_id) void client.invalidateQueries({ queryKey: queryKeys.employeeTasks(task.assignee_id) }); } }); }
export function useUpdateTask() { const client = useQueryClient(); return useMutation({ mutationFn: ({ projectId, taskId, body }: { projectId: string; taskId: string; body: Parameters<typeof api.updateTask>[2] }) => api.updateTask(projectId, taskId, body), onSuccess: (task, variables) => { void client.invalidateQueries({ queryKey: queryKeys.task(variables.projectId, variables.taskId) }); void client.invalidateQueries({ queryKey: queryKeys.projectTasks(variables.projectId) }); invalidateProject(client, variables.projectId); if (task.assignee_id) void client.invalidateQueries({ queryKey: queryKeys.employeeTasks(task.assignee_id) }); } }); }